name: Linter Check

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: ⬇️ Cloner le repository
        uses: actions/checkout@v4

      - name: 📦 Installer les dépendances
        run: npm install

      - name: 🔍 Exécuter le linter
        run: scripts/pre-commit.sh
